### ISSUE TITLE
celebrities

### ISSUE THREAD

**Issue by zkhan93** [moviepediafilms/moviepediafilms.com#148]
```
[
    {
        "title": "Actor",
        "name": "Sindhu Sreenivasa Murthy",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/w_380,h_270/v1600785908/judges_thumbs/20200922_201207_0000_t2rtbd.png",
        "about": "Sindhu Sreenivasa Murthy is an actress and casting director, known for Bisht, Please! (2017), Brahman Naman (2016) and French Biriyani (2020). She also works actively in the theatre industry. She is best known for her work in the play Open."
    },
    {
        "title": "Actor",
        "name": "Vipin Sharma",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/w_380,h_270/v1600784097/judges_thumbs/20200922_182607_0000_dwlpn2.png",
        "about": "Vipin Sharma is an Indian film actor known for his works predominantly in Hindi cinema. He is an alumnus of National School of Drama, New Delhi, India and the Canadian Film Centre, Toronto, Ontario, Canada."
    },
    {
        "title": "Actor",
        "name": "Niharika Lyra Dutt",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/w_380,h_270/v1600784095/judges_thumbs/20200922_182642_0000_ispwzr.png",
        "about": "Niharika Lyra Dutt is an actor and a model.The actor featured in the 2018 Amazon Prime's web series Die Trying. She's also appeared in Amazon's hit web series, Pataal Lok. Her acting prowess has been hailed by the critics and audience alike."
    },
    {
        "title": "Director",
        "name": "Bejoy Nambiar",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/w_380,h_270/v1600784095/judges_thumbs/20200922_182626_0000_osijza.png",
        "about": "Bejoy Nambiar (born 12 April 1979) is an Indian film director, and screenwriter who is known for his feature film debut film, Shaitan (2011). His second feature film was a bilingual gangster-comedy film called David. His latest Bollywood film was Wazir (2016), starring Amitabh Bachchan and Farhan Akhtar."
    },
    {
        "title": "Casting Director",
        "name": "Shubham Gaur",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785910/judges_thumbs/20200922_193412_0000_s8zlxk.png",
        "about": "Shubham has worked as a non-fiction writer in UTV And NDTV imagine for 2 yrs. It has been 10 years since he's been working as casting director in Mumbai. Some of his work includes The Lunchbox, Sense8, The Jungle Book, etc."
    },
    {
        "title": "Founder, Humans of Cinema",
        "name": "Harshit Bansal",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785909/judges_thumbs/20200922_193347_0000_r2wgnw.png",
        "about": "Harshit is the founder and curator of 'Humans of Cinema', a digital film appreciation platform where cinephiles have conversations around their favorite films and the impact of cinema. He also hosts a film podcast where he chats with film artists about their craft and their love for cinema."
    },
    {
        "title": "Writer",
        "name": "Pawan Sony",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785909/judges_thumbs/20200922_193654_0000_yb5ann.png",
        "about": "Pawan Sony has written for films like Stree (dir. Amar Kaushik) Dil Dosti Etc. (dir. Manish Tiwary), Sixteen (dir. Raj Purohit) and many more. He has published a graphic novel called Bhishma published by Holy Cow."
    },
    {
        "title": "Creative Writer/Director",
        "name": "Suganndha Mehrotra",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785908/judges_thumbs/20200922_194405_0000_fl7epl.png",
        "about": "Suganndha has worked as an Assistant Director for R. Balki in Paa and Second Assistant Director for Neeraj Pandey in films like Special 26, Baby. She has also worked as an Executive Producer in Homeshop18"
    }
]
```

**Comment by mavish014** [comment]
[
{
        "title": "Director",
        "name": "Mihir Desai",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384444/20201219_184254_0000_sqjl1i.png",
        "about": "Mihir Desai is an Indian filmmaker most recently known for directing two seasons of Amazon Prime Video's hit web-series "Mirzapur". Previously, Desai directed non-fiction TV shows "Man vs Job" S01, "OMG! Yeh Mera India" S03 for History-TV18 as well as "Kahi Suni" S01 for Epic Channel India."
    },
{
        "title": "Actor/Director",
        "name": "Vipin Sharma",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184543_0000_ud4db8.png",
        "about": "Vipin Sharma is an Indian film actor known for his works predominantly in Hindi cinema. As an actor and editor, he’s known for films like Taare Zameen Par (2007), Gangs of Wasseypur (2012) and Hotel Mumbai (2018). He is also an alumnus of National School of Drama, New Delhi, India and the Canadian Film Centre, Toronto. Recently, he made his directorial debut with an experimental short film, Missing that got   screened in New York Indian Film Festival "
    },
{
        "title": "Director",
        "name": "Dar Gai",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184640_0000_i0ypxe.png",
        "about": "Born and brought up in Ukraine, Dar Gai is the writer/director of 'Teen aur Aadha' and 'Namdev Bhau' and has been named one of the top 15 female filmmakers of the last decade by Taste of Cinema. Dar's ventures include several clutter-breaking music videos, like 'Kasoor', 'Cold/Mess', ‘Liggi’ with celebrated Indie artists like Prateek Kuhad and Ritviz. "
    },




    {
        "title": "Actor",
        "name": "Sindhu Sreenivasa Murthy",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384444/20201219_184843_0000_aigffi.png",
        "about": "Sindhu Sreenivasa Murthy is an actress and casting director, known for Bisht, Please! (2017), Brahman Naman (2016) and French Biriyani (2020). She also works actively in the theatre industry. She is best known for her work in the play Open."
    },
    {
        "title": "Actor",
        "name": "Niharika Lyra Dutt",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184955_0000_vujgse.png",
        "about": "Niharika Lyra Dutt is an actor and a model. She featured in the 2018 Amazon Prime's web series Die Trying. She's also appeared in Amazon's hit web series, Pataal Lok. Her acting prowess has been hailed by the critics and audience alike."
    },
    {
        "title": "Casting Director",
        "name": "Shubham Gaur",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384445/20201219_185552_0000_ad2jwm.png",
        "about": "Shubham has worked as a non-fiction writer in UTV And NDTV imagine for 2 yrs. It has been 10 years since he's been working as casting director in Mumbai. Some of his work includes The Lunchbox, Sense8, The Jungle Book, etc."
    },

    {
        "title": "Director",
        "name": "Aashish Aryan ",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384447/20201219_185121_0000_jsu1sy.png",
        "about": "Aashish Aryan is a writer-director known for directing Hotstar feature length film, Kanpuriye. He’s written screenplay for award-winning film, T for Taj Mahal with Kireet Khurana. The film has won numerous accolades worldwide with winning 6 International awards and 20+ Official Selections in International Festivals. "
    },

    {
        "title": "Actor",
        "name": "Deeptesh Das",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_185318_0000_pjh9n1.png",
        "about": "Deeptesh Das is a professional Indian actor acclaimed for his role as Constable Bhati in the 2020 television series, Pataal Lok. His other works include Hungry, an adaptation of William Shakespeare's Titus Andronicus which was screened in the Special Presentations section at the 2017 Toronto International Film Festival."
    },



    {
        "title": "Founder, Humans of Cinema",
        "name": "Harshit Bansal",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785909/judges_thumbs/20200922_193347_0000_r2wgnw.png",
        "about": "Harshit is the founder and curator of 'Humans of Cinema', a digital film appreciation platform where cinephiles have conversations around their favorite films and the impact of cinema. He also hosts a film podcast where he chats with film artists about their craft and their love for cinema."
    },
    {
        "title": "Writer",
        "name": "Pawan Sony",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785909/judges_thumbs/20200922_193654_0000_yb5ann.png",
        "about": "Pawan Sony has written for films like Stree (dir. Amar Kaushik) Dil Dosti Etc. (dir. Manish Tiwary), Sixteen (dir. Raj Purohit) and many more. He has published a graphic novel called Bhishma published by Holy Cow."
    },
    {
        "title": "Creative Writer/Director",
        "name": "Suganndha Mehrotra",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia/image/upload/v1600785908/judges_thumbs/20200922_194405_0000_fl7epl.png",
        "about": "Suganndha has worked as an Assistant Director for R. Balki in Paa and Second Assistant Director for Neeraj Pandey in films like Special 26, Baby. She has also worked as an Executive Producer in Homeshop18"
    }
]

**Comment by mavish014** [comment]
[
{
        "title": "Director",
        "name": "Mihir Desai",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384444/20201219_184254_0000_sqjl1i.png",
        "about": "Mihir Desai is an Indian filmmaker most recently known for directing two seasons of Amazon Prime Video's hit web-series "Mirzapur". Previously, Desai directed non-fiction TV shows "Man vs Job" S01, "OMG! Yeh Mera India" S03 for History-TV18 as well as "Kahi Suni" S01 for Epic Channel India."
    },
{
        "title": "Actor/Director",
        "name": "Vipin Sharma",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184543_0000_ud4db8.png",
        "about": "Vipin Sharma is an Indian film actor known for his works predominantly in Hindi cinema. As an actor and editor, he’s known for films like Taare Zameen Par (2007), Gangs of Wasseypur (2012) and Hotel Mumbai (2018). He is also an alumnus of National School of Drama, New Delhi, India and the Canadian Film Centre, Toronto. Recently, he made his directorial debut with an experimental short film, Missing that got   screened in New York Indian Film Festival "
    },
{
        "title": "Director",
        "name": "Dar Gai",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184640_0000_i0ypxe.png",
        "about": "Born and brought up in Ukraine, Dar Gai is the writer/director of 'Teen aur Aadha' and 'Namdev Bhau' and has been named one of the top 15 female filmmakers of the last decade by Taste of Cinema. Dar's ventures include several clutter-breaking music videos, like 'Kasoor', 'Cold/Mess', ‘Liggi’ with celebrated Indie artists like Prateek Kuhad and Ritviz. "
    },




    {
        "title": "Actor",
        "name": "Sindhu Sreenivasa Murthy",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384444/20201219_184843_0000_aigffi.png",
        "about": "Sindhu Sreenivasa Murthy is an actress and casting director, known for Bisht, Please! (2017), Brahman Naman (2016) and French Biriyani (2020). She also works actively in the theatre industry. She is best known for her work in the play Open."
    },
    {
        "title": "Actor",
        "name": "Niharika Lyra Dutt",
        "gender": "F",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_184955_0000_vujgse.png",
        "about": "Niharika Lyra Dutt is an actor and a model. She featured in the 2018 Amazon Prime's web series Die Trying. She's also appeared in Amazon's hit web series, Pataal Lok. Her acting prowess has been hailed by the critics and audience alike."
    },
    {
        "title": "Casting Director",
        "name": "Shubham Gaur",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384445/20201219_185552_0000_ad2jwm.png",
        "about": "Shubham has worked as a non-fiction writer in UTV And NDTV imagine for 2 yrs. It has been 10 years since he's been working as casting director in Mumbai. Some of his work includes The Lunchbox, Sense8, The Jungle Book, etc."
    },

    {
        "title": "Director",
        "name": "Aashish Aryan ",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384447/20201219_185121_0000_jsu1sy.png",
        "about": "Aashish Aryan is a writer-director known for directing Hotstar feature length film, Kanpuriye. He’s written screenplay for award-winning film, T for Taj Mahal with Kireet Khurana. The film has won numerous accolades worldwide with winning 6 International awards and 20+ Official Selections in International Festivals. "
    },

    {
        "title": "Actor",
        "name": "Deeptesh Das",
        "gender": "M",
        "image": "https://res.cloudinary.com/moviepedia-films/image/upload/v1608384441/20201219_185318_0000_pjh9n1.png",
        "about": "Deeptesh Das is a professional Indian actor acclaimed for his role as Constable Bhati in the 2020 television series, Pataal Lok. His other works include Hungry, an adaptation of William Shakespeare's Titus Andronicus which was screened in the Special Presentations section at the 2017 Toronto International Film Festival."
    },

]

**Comment by zkhan93** [comment]
updated list is maintained now on this [gist](https://gist.github.com/moviepedia/dc1349e485879fb53e91710be3e9fe3d) to be used only to create the profile any update must be done via admin panel
