### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by mavish014** [moviepediafilms/moviepediafilms.com#153]
Welcome to Moviepediafilms.com!
These terms and conditions outline the rules and regulations for the use of Moviepedia Films Website, located at https://www.moviepediafilms.com.

By Signing Up to this website we assume you accept these terms and conditions. Do not continue to use Moviepediafilms.com if you do not agree to take all of the terms and conditions stated on this document.

The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person logged on this website and compliant to the Company’s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to Moviepedia. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance, and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the expressed purpose of meeting the Client’s needs in respect of the provision of the Company’s stated services, in accordance with and subject to, prevailing law of the land. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to the same.

**Cookies**
We employ the use of cookies. By accessing Moviepediafilms.com, you agreed to use cookies in agreement with Moviepedia Films Privacy Policy.

Most interactive websites use cookies to let us retrieve the user’s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.

**License**
Unless otherwise stated, Moviepedia Films and/or its licensors own the intellectual property rights for all material on Moviepediafilms.com. All intellectual property rights are reserved. You may access this from Moviepediafilms.com for your own personal use subjected to restrictions set in these terms and conditions.
You must not:
•	Republish material from Moviepediafilms.com
•	Sell, rent, or sub-license material from Moviepediafilms.com
•	Reproduce, duplicate, or copy material from Moviepediafilms.com
•	Redistribute content from Moviepediafilms.com
This Agreement shall begin on the date hereof.
Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Moviepedia does not filter, edit, publish, or review Comments prior to their presence on the website. 
Comments do not reflect the views and opinions of Moviepedia Films, its agents, and/or affiliates. Comments reflect the views and opinions of the person who posts their views and opinions. To the extent permitted by applicable laws, Moviepedia Films shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the comments on this website.

Moviepedia Films reserves the right to monitor all comments and to remove any comments which can be considered inappropriate, offensive, or cause a breach of these Terms and Conditions.

You warrant and represent that:
•	You are entitled to post the comments on our website and have all necessary licenses and consents to do so;
•	The comments do not invade any intellectual property right, including but without limitation copyright, patent, or trademark of any third party;
•	The comments do not contain any defamatory, libelous, offensive, indecent, or otherwise unlawful material which is an invasion of privacy
•	The comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.
•	You hereby grant Moviepedia Films a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats, or media.

**Hyperlinking to our Content**
The following organizations may link to our Website without prior written approval:
•	Government agencies;
•	Search engines;
•	News organizations;
Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses and links of the social media pages of Moviepedia will be listed on the website.

Approved organizations may hyperlink to our Website as follows:
•	By use of our corporate name; or
•	By use of the uniform resource locator being linked to; or
•	By use of any other description of our Website being linked to shall make sense within the context and format of content on the linking party’s site.
No use of Moviepedia Films’ logo or other artwork will be allowed for linking absent a trademark license agreement.

**Content Liability**
We shall not be held responsible for any content that appears on your website. You agree to protect and defend us against all claims that are rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.

**Your Privacy**
Please read Privacy Policy [here](https://moviepediafilms.com/privacy-policy). 

**Reservation of Rights**
We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amend these terms and conditions and its linking policy at any time. By continuously linking to our website, you agree to be bound to and follow these linking terms and conditions.

**Removal of links from our website**
If you find any link on our website that is offensive for any reason, you are free to contact and inform us at any moment. We will consider requests to remove links but we are not obligated to do so or to respond to you directly.

We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.

**Disclaimer**
To the maximum extent permitted by applicable law, we exclude all representations, warranties, and conditions relating to our website and the use of this website. Nothing in this disclaimer will:

•	limit or exclude our or your liability for death or personal injury;
•	limit or exclude our or your liability for fraud or fraudulent misrepresentation;
•	limit any of our or your liabilities in any way that is not permitted under applicable law; or
•	exclude any of our or your liabilities that may not be excluded under applicable law.
The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort, and for breach of statutory duty.

**Comment by zkhan93** [comment]
updated please verify @mavish014
