### ISSUE TITLE
Film Page 

### ISSUE THREAD

**Issue by mavish014** [moviepediafilms/moviepediafilms.com#27]
Summarizing the tasks

## TODOs
- [x] Review button should be before all the reviews
- [x] Bookmark button is redundant, make it a recommends button, user will recommend a movie by clicking this button, a users recommended movies can be seen in his profile page under a "Recommends" tag.

## Under discussion TODOs
- Only 100 characters of each review should be visible, with a read more link: 
     - what will be the action attached to that show more link ? a new page ? or an external website link ?
     - the read more button on [https://www.rottentomatoes.com/m/last_days](https://www.rottentomatoes.com/m/last_days) is opening reviews published on different(other than www.rottentomatoes.com) platforms

**Comment by mavish014** [comment]
https://www.rottentomatoes.com/m/last_days

Visit link

**Comment by mavish014** [comment]
![Screenshot_2020-10-08-12-41-10-83](https://user-images.githubusercontent.com/72265101/95426814-2d84f580-0964-11eb-880d-3c51d09419ce.jpg)
![Screenshot_2020-10-08-12-45-54-12](https://user-images.githubusercontent.com/72265101/95426831-3b3a7b00-0964-11eb-9840-9fb19cb04c64.jpg)
![Screenshot_2020-10-08-12-45-51-25](https://user-images.githubusercontent.com/72265101/95426834-3d043e80-0964-11eb-9bfa-86d21e5baaf8.jpg)


We'll record a recommend list from every user. MATLAB a user can tap on a recommend button and that film arrive on his recommends tab

So we'll have these three tabs Watchlist Earnings Recommends 

Bookmark button will be Recommends Button

**Comment by zkhan93** [comment]
all the things discussed on this page are complete, for profile related comments discuss on #7
