### ISSUE TITLE
Engagement Score & Popularity Score 

### ISSUE THREAD

**Issue by mavish014** [moviepediafilms/moviepediafilms.com#54]
[MoviepediaFilms.docx](https://github.com/moviepediafilms/moviepediafilms.com/files/5438770/MoviepediaFilms.docx)

**Comment by zkhan93** [comment]
## Audience Private Profile:
### Engagement Score:
#### Movie Specific :

Coponents | How to 			Measure | Maximum | Formula
-- | -- | -- | --
review | No of letters | 1.00 | Upto 140 words 			0.5 and above it 1 point
Deviation | Similarity with 			jury score | 1.50 | 1.5-.15*(deviation)
up votes | no of upvotes | 1.25 | increase in 0.01 			wirth every increase in like/upvote but, limited to 125
  |   | 3.75 |  

#### Time Specific :
Every 4 minutes spent on a film page per session gives rise to 1 point in engagement score.


### Levels:
Level 1: 0-656.25
Level 2: 656.26-2843.75
Level 3: 2843.76-8468.75
Level 4: 8468.76-16468.75
Level 5: 16468.76-32093.75


Lower Limit | Upper Limit | Movie 			Specific (Max Points that could be added per level) .60*UL | Time Specific 			(Max Points that could be added per level) .40*UL
-- | -- | -- | --
0 | 656.25 | 393.75 | 262.5
656.26 | 2843.75 | 1706.25 | 1137.5
2843.76 | 8468.75 | 5081.25 | 3387.5
8468.76 | 16468.75 | 9881.25 | 6587.5
16468.76 | 32093.75 | 19256.25 | 12837.5


    • Movie Specific Upper Limit for any level is 60 percent of Cumulative Score (if less than equal to upper limit then engagement score gets added up from that particular component)
    • Time Specific Upper Limit for any Level is 40 percent of Cumulative Score (if less than equal to upper limit then engagement score gets added up from that particular component)

Constraint = 1 REVIEW PER 1 UNIQUE USER FOR EACH FILM 


## Filmmaker Private Profile:
### Popularity Score:
#### Part A | Overall
2 points per follow received.

#### Part B | 
##### Fixed Component:
Moviepedia Rating out of 10 [weightage 10=25] Maximum 25 points

##### Variable Component:

Component | limit | per unit | points
-- | -- | -- | --
Page Views | 100 | 0.1 | 10
Total reviews | 20 | 1 | 20
Ratings (>=7 			only) | 50 | 0.5 | 25


###Levels (Fund-Ready Meter)

Level of 			completion | Popularity 			Score (Cumulative) | 80% (part B) | 20% (part A)
-- | -- | -- | --
10.00% | 640 | 512 | 128
25.00% | 1600 | 1280 | 320
50.00% | 3200 | 2560 | 640
75.00% | 4800 | 3840 | 960
100.00% | 6400 | 5120 | 1280

**Comment by zkhan93** [comment]
```
Time Specific :
Every 4 minutes spent on a film page per session gives rise to 1 point in engagement score.
```
I don't think this is a good metric to collect and give points on, ppl can leave the film page open for getting max points

**Comment by zkhan93** [comment]
for both engagement score, popularity score the logic is in place, there are 2 jobs that run at midnight IST to recalculate engagement scores, and popularity score of the users.
