### ISSUE TITLE
Leaderboard page

### ISSUE THREAD

**Issue by moviepediafilms** [moviepediafilms/moviepediafilms.com#6]
Ideas for leaderboard page goes here
![WhatsApp Image 2020-10-02 at 3 38 49 PM](https://user-images.githubusercontent.com/53233201/94913911-b5cc4c00-04c7-11eb-9470-669ac6f5a747.jpeg)

**Comment by zkhan93** [comment]
audience and filmmaker leaderboard design is done and delivered
