### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by moviepediafilms** [moviepediafilms/moviepediafilms.com#7]
## Profile page layout for Non-Director members
<img src="https://user-images.githubusercontent.com/53233201/94913790-7b62af00-04c7-11eb-9a5d-c109ea4b3239.jpeg" width="400"/>

### Interactions
- Isme upar hee reviews dikha denge. Neeche tab me filmmakers jo follow kar rha unke naam honge
- Upar sab tappable hoga. Rank jo hai uspe click karega to audience leaderboard (based on earnings) reviews click karega to usne jo reviews likhe
- Level click kia to bas ek chota sa hover 1/5 levels unlocked

## Profile page layout for Director
<img src="https://user-images.githubusercontent.com/72265101/94939699-1ec7ba00-04f0-11eb-8f61-ade7de7aee35.png" width="400"/>

**Comment by mavish014** [comment]
![20201002_153110_0000](https://user-images.githubusercontent.com/72265101/94939699-1ec7ba00-04f0-11eb-8f61-ade7de7aee35.png)

**Comment by mavish014** [comment]
Film Crew Members ke liye
ek tab add hoga: FILMOGRAPHY 

isme movies jisme wo kaam kiya hai. with his role in the filme (Producer/Director/Actor)

**Comment by mavish014** [comment]
**Audience Private Profile**

Elements: 
Earnings (month end pe update hoga tab tak) hyphen  (-)
Watchlist Recommends Lists 
Rest of the elements same as above poster

**Audience Public Profile** 
Recommends Lists 

rest same as above poster except engagement meter will be hidden 

**Filmmaker Private Profile** 
Same as the above poster 

**Filmmaker Public Profile**

Filmmaker as the above poster 
Except Fund-ready meter hidden, performance hidden,
Only one tab: Filmography 

**Film Crew Members (Non-Director) ** 
ek tab add hoga in Audience Public/Private Profile : FILMOGRAPHY

isme movies jisme wo kaam kiya hai. with his role in the filme (Producer/Director/Actor)

**Comment by mavish014** [comment]
Filmmaker Profile mein Naam ke aage ek filmmaker icon rahega (Like we're watching his filmmaker profile)
Crew Member k lie alag icon hoga (general films ka icon)
Audience has no icon.

**Comment by mavish014** [comment]
**Audience Private Profile**

**Elements:**
Earnings (month end pe update hoga tab tak) hyphen (-)
Watchlist Recommends Lists
Rest of the elements same as above poster

**Audience Public Profile**
Recommends Lists

rest same as above poster except engagement meter will be hidden

**Filmmaker Private Profile**
Same as the above poster

**Filmmaker Public Profile**

Filmmaker as the above poster
Except Fund-ready meter hidden, performance hidden,
Only one extra tab (audience public profile in context) : Filmography

**Film Crew Members (Non-Director) **
ek tab extra add hoga in Audience Public/Private Profile : FILMOGRAPHY

isme movies jisme wo kaam kiya hai. with his role in the filme (Producer/Director/Actor)

**Comment by mavish014** [comment]
![20201027_024205_0000](https://user-images.githubusercontent.com/72265101/97229226-06507400-17fe-11eb-8ae1-5469657c2365.png)
 Filmmaker Private Profile (Now Playing hatake Filmography)

**Comment by mavish014** [comment]
Wo drop-down wala arrow pe click kre to (1/5 levels unlocked )

**Comment by mavish014** [comment]
In both profiles extra two tabs to be added 
Followers and Following List.

**Comment by zkhan93** [comment]
will will be the contents of this "Filmography" tab ?

**Comment by zkhan93** [comment]
Summarizing the tabs in different views 

## When viewer is not logged in
- [x] only photo and name is visible
- [x] all tabs hidden

## When viewer is logged in

### Audience Public
- [x] Engagement Meter hidden
- [x] Recommends
- [x] Lists
- [x] Followers
- [x] Following
- [ ] Filmography

### Audience Private
- [x] Engagement Meter visible
- [x] Profile Picture Edit button
- [x] Watchlist
- [x] Recommends
- [x] Lists
- [x] Followers
- [x] Following
- [ ] Filmography

### Filmmaker Public
- [ ] Now Playing
- [x] Fund Ready meter hidden 

### Filmmaker Private
- [x] Profile Picture editable
- [x] Fund Ready meter visible
- [ ] Performace
- [ ] Reviews
- [ ] Filmography

**Comment by zkhan93** [comment]
the items discussed here are added to the profile views, issues with any of the feature should be tracked seperately
